### ISSUE TITLE
Composer could not find the package

### ISSUE THREAD

**Issue by metaclass-nl** [Angel-Source-Labs/laravel-spatial#1]
composer require angel-source-labs/laravel-spatial

resulted in:

In PackageDiscoveryTrait.php line 383:
                                                                               
  Could not find a matching version of package angel-source-labs/laravel-spat  
  ial. Check the package spelling, your version constraint and that the packa  
  ge is available in a stability which matches your minimum-stability (dev).   
      
Maybe because angel-source-labs/laravel-spatial is not on
https://packagist.org/packages/angel-source-labs/ ?

**Comment by bfinlay** [comment]
Yes you are correct.   I was considering changing the name before putting it on packagist, but I hadn’t come up with a good name and I can change it later if I do. 

I have added it to packagist. 

Let me know how it works for you.

**Comment by bfinlay** [comment]
This has been updated for Laravel 11.x and all tests are passing.

We support this package because we use it in our own product,  and we just completed updating to Laravel 11.

I am closing this issue.   If you have used it, feel free to add a comment and let us know how it has worked for you.
